---
- name: flask demo
  hosts: all

  tasks:
    - name: install Python on Ubuntu
      become: yes
      apt:
        name:
          - python3
          - python3-devel
          - python3-pip
          - python-setuptools
        state: present
      when: ansible_facts['distribution'] == 'Ubuntu'
    
    - name: install Python on CentOS
      become: yes
      yum:
        name: "{{ packages }}"
      vars:
        packages:
          - python3
          - python3-devel
          - python3-pip
          - python-setuptools
        state: present
      when: ansible_facts['distribution'] == 'CentOS'

    - name: install git
      become: true
      package:
        name: git
        state: latest

    - name: checkout source code from github
      git:
        repo: 'https://github.com/xiaopeng163/flask-ansible-demo'
        dest: ~/flask-ansible-demo

    - name: pip install requirements
      pip:
        requirements: ~/flask-ansible-demo/requirements.txt
        state: present
        virtualenv: ~/flask-ansible-demo/.env
        virtualenv_command: /usr/bin/python3 -m venv

    - name: start flask app
      shell: nohup ~/flask-ansible-demo/.env/bin/python ~/flask-ansible-demo/wsgi.py&
      register: myoutput

    - name: print stdout
      debug:
        var: myoutput
      